### General ###
mode: training   # training / hparam_tuning / generation
jobtype: ...
seed: 42

### Dataset ###
path: ...
pickle_file: ...
atom_type: ['H', 'C', 'N', 'O', 'F']
boltzmann_weight: False
batch_size: 32
num_workers: 4
split_method: manual
split_file: ...
train_size: 0.6
val_size: 0.2

### Model ###
pretrained_model: null
sigma_embed_dim: 32
sigma_min: 0.0314
sigma_max: 3.14
sh_lmax: 2
ns: 32
nv: 8
num_conv_layers: 4
max_radius: 5.0
radius_embed_dim: 50
scale_by_sigma: True
use_second_order_repr: True
batch_norm: True
residual: True
optimizer: Adam
lr: 0.001
scheduler:
  type: ReduceLROnPlateau
  factor: 0.7
  patience: 20
  min_lr: 0.00001

### Training ###
epoch_num: 250
output_step: 1
model_save_step: 50
early_stopping:
  patience: 20
  delta: 0

### generation ###
test_csv: ...
pre_mmff: False
post_mmff: False
seed_confs: ...
single_conf: False
inference_steps: 20
ode: False
dump_pymol: False

### evaluation ###
true_confs: ...
gen_confs: ...
